### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by dlruawo07** [dlruawo07/hw_lv2#1]
저번에 말씀해주신 errorHandler와 validation 관련 라이브러리를 활용한 유효성 검사는 다음 과제부터 공부해보겠습니다.

사실 지난 과제의 연장선이기도 하고 추가된 기능인 회원가입/로그인은 강의에 잘 나와있어서 크게 궁금한 점은 없는 것 같습니다.
한 가지 있다면, 게시글/댓글 수정/삭제 API에서 수정/삭제에 실패한 경우 "수정/삭제가 정상적으로 처리되지 않았습니다" 에러메세지를 반환해야하는데
```
const deleted = await Post.deleteOne();
const updated = await Comment.updateOne();

if (!deleted)
if (!updated)
```

이런 식으로 변수에 따로 담아줘서 업데이트나 딜리트가 실패한 경우로 처리를 했는데 이렇게 해도 괜찮은 걸까요?

또 한 가지 궁금한 점이 있다면 권한 검사를 할 때 authMiddleware에서 받아온 userId를 수정/삭제하고자 하는 post/comment의 userId랑 비교를 했는데 괜찮은 방법인가요? 아니라면 어떤 식으로 검사를 하는 게 좋을까요?

**Comment by dlruawo07** [comment]
위의 코드 부분은 3레벨 과제부터는 db 명령어에서 catch로 처리해주는 방식으로 바꿨습니다!

**Comment by ohbin-kwon** [comment]
1. 첫번째 질문에 대한 답변
아래의 답변에서도 catch로 처리해주는 방식으로 바꿧다고 말씀해주셨는데, 레벨2과제에서 동일하게 적용가능합니다. catch를 사용할 수 있는것은 promise일때 모두 가능하니까요!!
답이 있는것은 아니니 try catch를 사용해도 될것이고, promise가 reject된것을 catch르 이용해 처리를 해줘도 될것입니다. db명령어에서 catch를 해주는 방식으로 바꾸셨다는 말씀이, promise를 이해하고 사용하신것인지 궁금하네요. 요기에 답변달아주셔도 되고, 순회때 이야기 나눠봐도 좋을것같습니다!

2. 두번째 질문(userId와 post/comment userId 비교)
질문하신 의도가 좀더 명확하면 좋을것같습니다. 비교가 필요하다면 적절하게 추론해보면 좋을것같아요.
목적: post/comment를 삭제할때 필요한 정보 또는 조건은 무엇인가?
추론1- 해당 api를 사용하는 주체는 누구인가?
추론2- authmiddleware로 받아온 userId로 우리가 알수있는 정보는 무엇일까?
추론3- post/comment의 userId는 어떤 정보인가?

이런식으로 목적과 추론을 통해서 결론에 도달하는 과정을 연습해보면 좋을것같습니다. 해당과정을 진행해보시고, 결론을 도출해서 답변달아주시거나 순회시간에 말씀해주세요

**Comment by ohbin-kwon** [comment]
코드는 깔끔하게 잘 작성하신듯합니다. 레벨 3리뷰때 뵙겠습니다!
